<?php
$lang[mg_editing] = "Editing MemberGroups";
$lang[mg_newgrpname] = "New group name";
$lang[mg_grpname] = "Group Name";
$lang[mg_grpdesc] = "Group Description";
$lang[mg_userlist] = "Group's user list";
$lang[mg_adminlist] = "Group admins";
$lang[mg_er_grp_exist] = "Error : Group already exists !";
$lang[mg_er_grp_exist2] = "Error : A username with the same name as this group already exists !";
$lang[mg_grpupdated] = "Group added / updated successfully.";
$lang[mg_grpdeleted] = "Group deleted.";
$lang[mg_textgroups] = "Groups";
$lang[mg_er_no_email] = "Error : You must have an email address stored in your profile to send a group email.";
$lang[mg_msg_not_sent] = "not found, message not sent.";
$lang[mg_sent_to_user] = "sent to Username";
$lang[mg_email_address_for_user] = "email address for user";
$lang[mg_email_conf_1] = "You sent the following email message to the following users";
$lang[mg_email_conf_2] = "Email sent to your email address";
$lang[mg_email_conf_3] = "as a reminder.<br>Your email is sent with the others so they should arrive together.";
$lang[mg_no_group_admin] = "Sorry, you are not an admin for any groups.";
$lang[mg_no_groups] = "There are currently no groups. Type a new group name in the box below and click Submit to make one.";
$lang[mg_er_grp_bad_char] = "Bad Character in group name. Characters allowed : a-z, A-Z, 0-9, Minus (-) and Underscore (_)"
?>