<html>
<head>
<title>Untitled Document</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body bgcolor="#FFFFFF" text="#000000">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="40%">&nbsp;</td>
    <td width="35%">&nbsp;</td>
    <td width="25%">&nbsp;
      <? include ("vote.php"); ?>
    </td>
  </tr>
</table>
</body>
</html>
