<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	<title>Skate World</title>
<style type="text/css">
body {scrollbar-base-color:003388;
	 scrollbar-track-color:003388;
	 scrollbar-arrow-color:6699cc;
	 scrollbar-shadow-color:ffffff; 
	 scrollbar-dark-shadow-color:6699cc; 
	 scrollbar-3dlight-color:ffffff; 
	 scrollbar-highlight-color:003388;}
a {color:#ffffff; text-decoration:none;}
a:hover {color:#ffffff; text-decoration:none; filter:glow(color=#0575a5,offX=5, offY=5); height:12; }
h3, h2 {color:#ffffff; text-decoration:none; filter:glow(color=#8C1313,offX=5, offY=5); height:12; }
</style>
</head>
<body bgcolor="#003366" text="#ffffff" scroll="auto"><font face="Arial Narrow">
<form method="post" action="process.php">
First Name        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                           <input name="first_name"   type="text"     style=" border-color:#6699cc; width:100px;height:20px;background-color:003366;color:#f3fe1e;font-size:8pt; font-family:Arial;border-style:dashed;">  <br>   <br>
E-mail            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input name="email"        type="text"     style=" border-color:#6699cc; width:100px;height:20px;background-color:003366;color:#f3fe1e;font-size:8pt; font-family:Arial;border-style:dashed;">  <br>   <br>
Site Name         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                                     <input name="site_name"    type="text"     style=" border-color:#6699cc; width:100px;height:20px;background-color:003366;color:#f3fe1e;font-size:8pt; font-family:Arial;border-style:dashed;">  <br>   <br>
Country           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             <input name="country"      type="text"     style=" border-color:#6699cc; width:100px;height:20px;background-color:003366;color:#f3fe1e;font-size:8pt; font-family:Arial;border-style:dashed;">  <br>   <br>
Password          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                               <input name="password"     type="password" style=" border-color:#6699cc; width:100px;height:20px;background-color:003366;color:#f3fe1e;font-size:8pt; font-family:Arial;border-style:dashed;">  <br>   <br>
Re-enter password &nbsp;&nbsp;                                                                                                                   <input name="new_password" type="password" style=" border-color:#6699cc; width:100px;height:20px;background-color:003366;color:#f3fe1e;font-size:8pt; font-family:Arial;border-style:dashed;">  <br>   <br>
Package           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                   <input name="package"      type="text"     style=" border-color:#6699cc; width:100px;height:20px;background-color:003366;color:#f3fe1e;font-size:8pt; font-family:Arial;border-style:dashed;">  <br>   <br>
<input type="submit" value="Submit"  style=" border-color:#6699cc; width:50px;height:20px;background-color:003366;color:#ffffff;font-size:8pt; font-family:Arial;">
</form>

</body>
</html>
