<table width="650" border="0" cellspacing="1" cellpadding="2" bgcolor="#dcdcdc" align="center">
<tr><td bgcolor="whitesmoke" colspan="2">
<center><b>Saturday, April 19 2003</b></center>
</td></tr>
<tr><td bgcolor="#ffffff" colspan="2">
<a id="fus_1" name=""><table width="650" border="0" cellspacing="1" cellpadding="2" bgcolor="#dcdcdc" align="center">
  <tr>
    <td bgcolor="whitesmoke" colspan="2">
      <p><b>Welcome to Fusion News 3.6.1</b> posted by <a href="mailto:support@fusionphp.com">FusionPHP Team</a> on 04-19-2003 16:37</p>
    </td>
  </tr>
  <tr>
    <td bgcolor="#ffffff" colspan="2">
      <p>Hi,<br><br>And welcome  <img src="http://www.truevisionary.be/news2/smillies/cheesy.gif
">  <br>You have just succeeded in installing Fusion News 3.6.1. Congratulations <img src="http://www.truevisionary.be/news2/smillies/smile.gif
"> <br>The Fusion Team thanks you for using this software and hopes everything will work smooth for you.<br><br>Regards,<br>The Fusion Team.</p><br><a href="http://www.truevisionary.be/news2/comments.php?id=1">comments</a>: 0<br><a href="http://www.truevisionary.be/news2/send.php?id=1">send to friend</a><br>
    </td>
  </tr>
</table>
<br>

</td></tr></table><br>