<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	<title>Skate World</title>
<style type="text/css">
body {scrollbar-base-color:003388;
	 scrollbar-track-color:003388;
	 scrollbar-arrow-color:6699cc;
	 scrollbar-shadow-color:ffffff; 
	 scrollbar-dark-shadow-color:6699cc; 
	 scrollbar-3dlight-color:ffffff; 
	 scrollbar-highlight-color:003388;}
a {color:#ffffff; text-decoration:none;}
a:hover {color:#ffffff; text-decoration:none; filter:glow(color=#0575a5,offX=5, offY=5); height:12; }
h3, h2 {color:#ffffff; text-decoration:none; filter:glow(color=#8C1313,offX=5, offY=5); height:12; }
</style>
</head>
<body bgcolor="#ffffff" text="#ffffff" scroll="auto">

<SCRIPT LANGUAGE="php">
    $email = $anonymous@skate-world.net;
    $mailto = "webmaster@skate-world.net";
    $mailsubj = "Comments about skate world";
    $mailhead = "From: anonymous@skate-world.net";
    reset ($HTTP_POST_VARS);
    $mailbody = "Comments: $comments\n";
    mail($mailto, $mailsubj, $mailbody, $mailhead);
</SCRIPT>

Thank you for sending in your comments.
<br><a href="www.skate-world.net">HOME</a>
</body>
</html>
