<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	<title>Skate World</title>
<style type="text/css">
body {scrollbar-base-color:003388;
	 scrollbar-track-color:003388;
	 scrollbar-arrow-color:6699cc;
	 scrollbar-shadow-color:ffffff; 
	 scrollbar-dark-shadow-color:6699cc; 
	 scrollbar-3dlight-color:ffffff; 
	 scrollbar-highlight-color:003388;}
a {color:#ffffff; text-decoration:none;}
a:hover {color:#ffffff; text-decoration:none; filter:glow(color=#0575a5,offX=5, offY=5); height:12; }
h3, h2 {color:#ffffff; text-decoration:none; filter:glow(color=#8C1313,offX=5, offY=5); height:12; }
</style>
</head>
<body bgcolor="#003366" text="#ffffff" scroll="auto">
<form method="post" action="process.php">
First Name:<br>
<input name="first_name"   type="text"     style=" border-color:#6699cc; width:186px;height:20px;background-color:003366;color:#f3fe1e;font-size:8pt; font-family:Arial;border-style:dashed;">  <br>   <br>
<font color="#fbb543">LIMITED OFFER:</font> Secret Username:<br>
<input type="text" name="secret" size=33 style=" border-color:#6699cc;background-color:003366;color:#f3fe1e;font-size:8pt; font-family:Arial;border-style:dashed;"><br><br>
E-mail:<br>
<input name="email"        type="text"     style=" border-color:#6699cc; width:186px;height:20px;background-color:003366;color:#f3fe1e;font-size:8pt; font-family:Arial;border-style:dashed;">  <br>   <br>
Term name:<br>
<input name="term"    type="text"     style=" border-color:#6699cc; width:186px;height:20px;background-color:003366;color:#f3fe1e;font-size:8pt; font-family:Arial;border-style:dashed;">  <br>   <br>
Explanation:<br>
<textarea name="explination" rows=3 cols=33  style=" border-color:#6699cc;background-color:003366;color:#f3fe1e;font-size:8pt; font-family:Arial;border-style:dashed;"></textarea><br><br>
<input type="submit" value="Submit"  style=" border-color:#6699cc; width:50px;height:20px;background-color:003366;color:#ffffff;font-size:8pt; font-family:Arial;">
</form>
</body>
</html>
